export const SOBJECTS      = 'PRODUCTS';
export const LOAD_SOBJECTS = 'LOAD_'+SOBJECTS;
export const LOAD_SUCCESS  = 'LOAD_SUCCESSFULLY_'+SOBJECTS;
export const LOAD_FAILED   = 'LOAD_FAILED_'+SOBJECTS;
export const SEARCH_TEXT_ENTERED = 'SEARCH_TEXT_ENTERED';
